site_name: Cours de Fonctionnement de l'ordinateur
site_url: https://tousignantsimon-Fonctionnement.github.io/
repo_url: hhttps://github.com/TousignantSimon-Fonctionnement/TousignantSimon-Fonctionnement.github.io.git

use_directory_urls: true

nav:
   - 'Accueil': index.md  
   - 'Horaire': horaire.md
   - 'Semaine 1': notes_de_cours/semaine_1/semaine_1.md
   - 'Semaine 2': notes_de_cours/semaine_2/semaine_2.md
   - 'Exercices': 
      - Semaine 1 : exercices/exercices_semaine_1.md
      - Semaine 2 : exercices/exercices_semaine_2.md
   - 'Logiciels requis': logiciels_requis.md
   - 'Raccourcis clavier' : raccourcis_clavier.md
      
theme:
  name: material
  icon:
    logo: fontawesome/solid/database
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.copy
    - toc.integrate
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Passer en mode sombre
      primary: indigo
      accent: teal
    - scheme: blue
      toggle:
        icon: material/toggle-switch
        name: Passer en mode clair
      primary: indigo
      accent: light blue
plugins:
  - search: {}

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/alltarget.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.escapeall:
      hardbreak: true # use \ to create new line
      nbsp: true # use \<space> to create &nbsp;
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - markdown_include.include:
      base_path: docs/tables
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


